import type { PiWebPlugin, ThemeTokens } from "@gang-of-beads/pi-web/plugin-api";

const classicTokens = {
  "--pi-bg": "#0d1117",
  "--pi-surface": "#161b22",
  "--pi-surface-hover": "#21262d",
  "--pi-terminal-bg": "#05070a",
  "--pi-terminal-text": "#e6edf3",
  "--pi-border": "#30363d",
  "--pi-border-muted": "#21262d",
  "--pi-text": "#e6edf3",
  "--pi-text-secondary": "#c9d1d9",
  "--pi-text-bright": "#f0f6fc",
  "--pi-muted": "#8b949e",
  "--pi-dim": "#6e7681",
  "--pi-accent": "#58a6ff",
  "--pi-accent-border": "#2f81f7",
  "--pi-selection-bg": "#0d2847",
  "--pi-success": "#3fb950",
  "--pi-success-border": "#238636",
  "--pi-success-bg": "#0f1b12",
  "--pi-success-surface": "#0f2a16",
  "--pi-success-ring": "#3fb95055",
  "--pi-warning": "#d29922",
  "--pi-warning-border": "#6e5200",
  "--pi-warning-surface": "#1f1a10",
  "--pi-danger": "#ff7b72",
  "--pi-purple": "#d2a8ff",
  "--pi-purple-border": "#a371f7",
  "--pi-purple-surface": "#21132f",
  "--pi-overlay": "#0008",
  "--pi-shadow-soft": "#0006",
  "--pi-shadow": "#0008",
  "--pi-shadow-strong": "#000b",
  "--pi-bg-overlay-soft": "#0d1117dd",
  "--pi-bg-overlay": "#0d1117e6",
  "--pi-success-bg-overlay": "#0f1b12ee",
  "--pi-terminal-selection": "#264f78",
} satisfies ThemeTokens;

const piWebDarkTokens = {
  "--pi-bg": "#070912",
  "--pi-surface": "#101527",
  "--pi-surface-hover": "#151b31",
  "--pi-terminal-bg": "#050710",
  "--pi-terminal-text": "#f7f4ff",
  "--pi-border": "#26304f",
  "--pi-border-muted": "#26304f",
  "--pi-text": "#f7f4ff",
  "--pi-text-secondary": "#aaa4bd",
  "--pi-text-bright": "#ffffff",
  "--pi-muted": "#aaa4bd",
  "--pi-dim": "#817a99",
  "--pi-accent": "#7c3cff",
  "--pi-accent-border": "#5a47b0",
  "--pi-selection-bg": "#1d2547",
  "--pi-success": "#00f0d8",
  "--pi-success-border": "#00f0d8",
  "--pi-success-bg": "#071e22",
  "--pi-success-surface": "#092d31",
  "--pi-success-ring": "#00f0d855",
  "--pi-warning": "#ffb000",
  "--pi-warning-border": "#ffb000",
  "--pi-warning-surface": "#16140d",
  "--pi-danger": "#ff4f7b",
  "--pi-purple": "#b7a2ff",
  "--pi-purple-border": "#7c3cff",
  "--pi-purple-surface": "#181026",
  "--pi-overlay": "#0008",
  "--pi-shadow-soft": "#0006",
  "--pi-shadow": "#0008",
  "--pi-shadow-strong": "#000b",
  "--pi-bg-overlay-soft": "#070912dd",
  "--pi-bg-overlay": "#070912e6",
  "--pi-success-bg-overlay": "#071e22ee",
  "--pi-terminal-selection": "#3d4a78",
} satisfies ThemeTokens;

const piWebLightTokens = {
  "--pi-bg": "#f7f1e6",
  "--pi-surface": "#fff9ee",
  "--pi-surface-hover": "#f0e6d6",
  "--pi-terminal-bg": "#15131b",
  "--pi-terminal-text": "#fff9ee",
  "--pi-border": "#c9bca8",
  "--pi-border-muted": "#d8cdbc",
  "--pi-text": "#15131b",
  "--pi-text-secondary": "#15131b",
  "--pi-text-bright": "#15131b",
  "--pi-muted": "#5f586a",
  "--pi-dim": "#766f7e",
  "--pi-accent": "#6430d8",
  "--pi-accent-border": "#6430d8",
  "--pi-selection-bg": "#eadff8",
  "--pi-success": "#008c82",
  "--pi-success-border": "#008c82",
  "--pi-success-bg": "#e1f4ef",
  "--pi-success-surface": "#d7f0ec",
  "--pi-success-ring": "#008c8255",
  "--pi-warning": "#b05f00",
  "--pi-warning-border": "#b05f00",
  "--pi-warning-surface": "#fff2d2",
  "--pi-danger": "#b51d49",
  "--pi-purple": "#6430d8",
  "--pi-purple-border": "#6430d8",
  "--pi-purple-surface": "#eadff8",
  "--pi-overlay": "#15131b66",
  "--pi-shadow-soft": "#15131b22",
  "--pi-shadow": "#15131b33",
  "--pi-shadow-strong": "#15131b44",
  "--pi-bg-overlay-soft": "#f7f1e6dd",
  "--pi-bg-overlay": "#f7f1e6e6",
  "--pi-success-bg-overlay": "#e1f4efee",
  "--pi-terminal-selection": "#8d7b64",
} satisfies ThemeTokens;

/**
 * Maximum legibility rather than atmosphere: near-black behind near-white, one
 * saturated accent, and state colours picked for contrast rather than mood.
 * For bright rooms, tired eyes, and anyone who finds the tinted themes muddy.
 */
const highContrastTokens = {
  "--pi-bg": "#000000",
  "--pi-surface": "#0d0d0d",
  "--pi-surface-hover": "#1a1a1a",
  "--pi-terminal-bg": "#000000",
  "--pi-terminal-text": "#ffffff",
  "--pi-border": "#5c5c5c",
  "--pi-border-muted": "#3d3d3d",
  "--pi-text": "#ffffff",
  "--pi-text-secondary": "#e6e6e6",
  "--pi-text-bright": "#ffffff",
  "--pi-muted": "#b3b3b3",
  "--pi-dim": "#8f8f8f",
  "--pi-accent": "#4dc3ff",
  "--pi-accent-border": "#4dc3ff",
  "--pi-selection-bg": "#00263a",
  "--pi-success": "#3ff05a",
  "--pi-success-border": "#3ff05a",
  "--pi-success-bg": "#001a06",
  "--pi-success-surface": "#00280b",
  "--pi-success-ring": "#3ff05a66",
  "--pi-warning": "#ffcc33",
  "--pi-warning-border": "#ffcc33",
  "--pi-warning-surface": "#251c00",
  "--pi-danger": "#ff6b6b",
  "--pi-purple": "#c9a3ff",
  "--pi-purple-border": "#c9a3ff",
  "--pi-purple-surface": "#180d29",
  "--pi-overlay": "#000000cc",
  "--pi-shadow-soft": "#00000099",
  "--pi-shadow": "#000000bb",
  "--pi-shadow-strong": "#000000e6",
  "--pi-bg-overlay-soft": "#000000dd",
  "--pi-bg-overlay": "#000000f2",
  "--pi-success-bg-overlay": "#001a06ee",
  "--pi-terminal-selection": "#00456b",
} satisfies ThemeTokens;

/**
 * A dark theme for a dark room: warm, desaturated, and deliberately dim. The
 * accent is amber rather than blue because blue is the part of the spectrum
 * that keeps you awake, and nothing here is allowed to glare.
 */
const nightTokens = {
  "--pi-bg": "#14110e",
  "--pi-surface": "#1d1915",
  "--pi-surface-hover": "#26211b",
  "--pi-terminal-bg": "#100d0b",
  "--pi-terminal-text": "#e8ddcc",
  "--pi-border": "#3a3229",
  "--pi-border-muted": "#2b2520",
  "--pi-text": "#e8ddcc",
  "--pi-text-secondary": "#cbbfad",
  "--pi-text-bright": "#fff4e0",
  "--pi-muted": "#9c9081",
  "--pi-dim": "#7a6f62",
  "--pi-accent": "#e0a35c",
  "--pi-accent-border": "#b8813f",
  "--pi-selection-bg": "#2e2415",
  "--pi-success": "#8fbf6f",
  "--pi-success-border": "#6d9954",
  "--pi-success-bg": "#161c12",
  "--pi-success-surface": "#1e2718",
  "--pi-success-ring": "#8fbf6f55",
  "--pi-warning": "#d9a441",
  "--pi-warning-border": "#9c7429",
  "--pi-warning-surface": "#241c0f",
  "--pi-danger": "#d97b6c",
  "--pi-purple": "#b79ad1",
  "--pi-purple-border": "#8d74a8",
  "--pi-purple-surface": "#221a2b",
  "--pi-overlay": "#0a0806cc",
  "--pi-shadow-soft": "#00000055",
  "--pi-shadow": "#00000077",
  "--pi-shadow-strong": "#000000aa",
  "--pi-bg-overlay-soft": "#14110edd",
  "--pi-bg-overlay": "#14110ee6",
  "--pi-success-bg-overlay": "#161c12ee",
  "--pi-terminal-selection": "#3d3121",
} satisfies ThemeTokens;

/**
 * Ink on paper: a light theme with no tint, for daylight and for screenshots
 * that have to survive being printed or pasted into a document.
 */
const paperTokens = {
  "--pi-bg": "#fbfbf9",
  "--pi-surface": "#ffffff",
  "--pi-surface-hover": "#f1f1ee",
  "--pi-terminal-bg": "#1c1c1a",
  "--pi-terminal-text": "#fbfbf9",
  "--pi-border": "#c7c7c1",
  "--pi-border-muted": "#e0e0da",
  "--pi-text": "#1c1c1a",
  "--pi-text-secondary": "#33332f",
  "--pi-text-bright": "#000000",
  "--pi-muted": "#5e5e58",
  "--pi-dim": "#7c7c75",
  "--pi-accent": "#1f5fd0",
  "--pi-accent-border": "#1f5fd0",
  "--pi-selection-bg": "#e2ecfb",
  "--pi-success": "#0f7a4a",
  "--pi-success-border": "#0f7a4a",
  "--pi-success-bg": "#e6f5ed",
  "--pi-success-surface": "#d9efe3",
  "--pi-success-ring": "#0f7a4a55",
  "--pi-warning": "#8a5a00",
  "--pi-warning-border": "#8a5a00",
  "--pi-warning-surface": "#fdf0d5",
  "--pi-danger": "#b02020",
  "--pi-purple": "#5b3fc7",
  "--pi-purple-border": "#5b3fc7",
  "--pi-purple-surface": "#ece7fb",
  "--pi-overlay": "#1c1c1a66",
  "--pi-shadow-soft": "#1c1c1a1a",
  "--pi-shadow": "#1c1c1a2b",
  "--pi-shadow-strong": "#1c1c1a40",
  "--pi-bg-overlay-soft": "#fbfbf9dd",
  "--pi-bg-overlay": "#fbfbf9e6",
  "--pi-success-bg-overlay": "#e6f5edee",
  "--pi-terminal-selection": "#9ab4d8",
} satisfies ThemeTokens;

/**
 * Ink on warm paper, after Anthropic's published brand palette.
 *
 * Their four neutrals and three accents are used as given - dark #141413,
 * light #faf9f5, mid grey #b0aea5, light grey #e8e6dc, and orange #d97757,
 * blue #6a9bcc, green #788c5d. The rest of the ramp is interpolated from
 * those, and the few values that had to move did so to clear 4.5:1 against
 * their own background rather than for taste: the light theme's dimmest text
 * sat at 3.4:1, and the accents needed darkening on paper to be readable as
 * text rather than only as fills.
 */
const claySoftTokens = {
  "--pi-bg": "#141413",
  "--pi-surface": "#1f1e1c",
  "--pi-surface-hover": "#2a2825",
  "--pi-terminal-bg": "#0e0e0d",
  "--pi-terminal-text": "#faf9f5",
  "--pi-border": "#3a3833",
  "--pi-border-muted": "#2a2825",
  "--pi-text": "#faf9f5",
  "--pi-text-secondary": "#d6d3c9",
  "--pi-text-bright": "#ffffff",
  "--pi-muted": "#b0aea5",
  "--pi-dim": "#8a8880",
  "--pi-accent": "#d97757",
  "--pi-accent-border": "#c96442",
  "--pi-selection-bg": "#3a2a22",
  "--pi-success": "#8faa6c",
  "--pi-success-border": "#788c5d",
  "--pi-success-bg": "#161a12",
  "--pi-success-surface": "#1e2418",
  "--pi-success-ring": "#8faa6c55",
  "--pi-warning": "#d9a441",
  "--pi-warning-border": "#b8862f",
  "--pi-warning-surface": "#211c11",
  "--pi-danger": "#e0706b",
  "--pi-purple": "#6a9bcc",
  "--pi-purple-border": "#5081b4",
  "--pi-purple-surface": "#141d26",
  "--pi-overlay": "#0a0a09aa",
  "--pi-shadow-soft": "#00000059",
  "--pi-shadow": "#00000073",
  "--pi-shadow-strong": "#000000a6",
  "--pi-bg-overlay-soft": "#141413dd",
  "--pi-bg-overlay": "#141413e6",
  "--pi-success-bg-overlay": "#161a12ee",
  "--pi-terminal-selection": "#4a4038",
} satisfies ThemeTokens;

/** The same palette on paper: the canvas Anthropic writes on. */
const clayPaperTokens = {
  "--pi-bg": "#faf9f5",
  "--pi-surface": "#ffffff",
  "--pi-surface-hover": "#f0eee6",
  "--pi-terminal-bg": "#141413",
  "--pi-terminal-text": "#faf9f5",
  "--pi-border": "#d5d2c6",
  "--pi-border-muted": "#e8e6dc",
  "--pi-text": "#141413",
  "--pi-text-secondary": "#4a4842",
  "--pi-text-bright": "#000000",
  "--pi-muted": "#6b6860",
  "--pi-dim": "#767369",
  "--pi-accent": "#b4542f",
  "--pi-accent-border": "#b4542f",
  "--pi-selection-bg": "#f3e2d9",
  "--pi-success": "#55702f",
  "--pi-success-border": "#55702f",
  "--pi-success-bg": "#eef2e6",
  "--pi-success-surface": "#e4ebd7",
  "--pi-success-ring": "#55702f55",
  "--pi-warning": "#8a6413",
  "--pi-warning-border": "#8a6413",
  "--pi-warning-surface": "#f7edd8",
  "--pi-danger": "#a33a36",
  "--pi-purple": "#3f6f9f",
  "--pi-purple-border": "#3f6f9f",
  "--pi-purple-surface": "#e4edf5",
  "--pi-overlay": "#14141366",
  "--pi-shadow-soft": "#1414131a",
  "--pi-shadow": "#1414132b",
  "--pi-shadow-strong": "#14141340",
  "--pi-bg-overlay-soft": "#faf9f5dd",
  "--pi-bg-overlay": "#faf9f5e6",
  "--pi-success-bg-overlay": "#eef2e6ee",
  "--pi-terminal-selection": "#5a4a3e",
} satisfies ThemeTokens;

const themePackPlugin: PiWebPlugin = {
  apiVersion: 2,
  name: "PI WEB Themes",
  activate: () => ({
    contributions: {
      themes: [
        {
          id: "pi-web-dark",
          name: "PI WEB Dark",
          description: "Dark PI WEB palette.",
          order: 10,
          colorScheme: "dark",
          tokens: piWebDarkTokens,
        },
        {
          id: "pi-web-light",
          name: "PI WEB Light",
          description: "Light PI WEB palette.",
          order: 20,
          colorScheme: "light",
          tokens: piWebLightTokens,
        },
        {
          id: "classic",
          name: "PI WEB Classic",
          description: "The original PI WEB dark palette.",
          order: 30,
          colorScheme: "dark",
          tokens: classicTokens,
        },
        {
          id: "high-contrast",
          name: "High Contrast",
          description: "Near-black behind near-white, for bright rooms and tired eyes.",
          order: 40,
          colorScheme: "dark",
          tokens: highContrastTokens,
        },
        {
          id: "night",
          name: "Night",
          description: "Warm and dim, with an amber accent instead of blue light.",
          order: 50,
          colorScheme: "dark",
          tokens: nightTokens,
        },
        {
          id: "paper",
          name: "Paper",
          description: "Untinted ink on paper, for daylight and for screenshots.",
          order: 60,
          colorScheme: "light",
          tokens: paperTokens,
        },
        {
          id: "clay-soft",
          name: "Clay",
          description: "Warm ink and clay, after Anthropic's published palette.",
          order: 70,
          colorScheme: "dark",
          tokens: claySoftTokens,
        },
        {
          id: "clay-paper",
          name: "Clay Paper",
          description: "The same clay palette on its warm paper canvas.",
          order: 80,
          colorScheme: "light",
          tokens: clayPaperTokens,
        },
      ],
      themePairs: [
        {
          id: "pi-web",
          name: "PI WEB",
          description: "Follow the system light/dark preference with PI WEB themes.",
          order: 10,
          light: "pi-web-light",
          dark: "pi-web-dark",
        },
        {
          id: "clay",
          name: "Clay",
          description: "Follow the system light/dark preference with the clay palette.",
          order: 20,
          light: "clay-paper",
          dark: "clay-soft",
        },
      ],
    },
  }),
};

export default themePackPlugin;
